# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65da0d5597b1f997277b817197ef0ce648399d7b2ee337acce71a0ef73ef6c8490be234a5f39ebfcd598f205f35c55312a45036df643a64a60d3f00d97e10cbb

test:
  secret_key_base: 387359d100711a18077da20c8df0902d426866b212b044d6664d4e4d1d874d0248ec82fc873ed3909c9364c704882143d186d6f8b45ed544fd9d6c38eb7229a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
